<!--#include virtual="/header.htm" -->
<h2>Terms and conditions</h2>

Unfortunately the world as it is we must have Terms and Conditions.  By the way there is a great Movie called <a href="http://www.imdb.com/title/tt2084953/">Terms and Conditions May Apply</a>. Which Devels Deep into the complexities of our highly conditioned modern lives.  

Welcome to Antidote.org.nz (Antidote). Antidote.org.nz is a service of the Antidote Movement. Please read this Terms and Conditions of Use; by using this service, you acknowledge that you have read the terms and conditions of use and that you accept the terms of this agreement. YOU AGREE TO READ THESE TERMS AND CONDITIONS OF USE CAREFULLY BEFORE USING This Antidote Web Site. If you do not agree to these terms and conditions of use, you may not access or otherwise use this Antidote Web Site and should use your browser's "back" button to exit the Antidote Web Site.</br>
The Web is an evolving medium; we may change the terms of this agreement from time to time. By continuing to use the service after we post any such changes, you accept this agreement, as modified.</br>
</br>
Antidote.org.nz respects the privacy of our users. Please take a few minutes to review our Privacy Policy.</br>
</br>
We invite you to send in your questions or comments about Antidote.org.nz, or to bring to our attention any material you believe to be inaccurate. Please send such comments, including a copy of any material you wish to discuss, to Daniel Suter. who developed the website for the Antidote Movement. He can be contacted at dan@antidote.org.nz Shop 6 Carnaby lane, New Brighton, 8062, Christchurch, NZ</br>
</br>
If you are an owner of intellectual property who believes your intellectual property has been improperly posted or distributed via one of our Web sites, please notify us by sending a notice by NZ Mail to Antidote.org.nz in care of dan@antidote.org.nz Shop 6 Carnaby lane, New Brighton, 8062, Christchurch, NZ</br>
</br>
The material that appears on Antidote.org.nz is for informational purposes only. Despite our efforts to provide useful and accurate information, errors may appear from time to time. Before you act on information you've found on our site, you should confirm any facts that are important to your decision. Antidote.org.nz is not responsible for, and cannot guarantee the performance of, any products provided by the sites we may link. A link to another Web site does not constitute an endorsement of that site (nor of any product, service or other material offered on that site) by Antidote.org.nz or its licensors.</br>
</br>
We may change, suspend or discontinue any aspect of the Antidote Web Site at any time, including the availability of any WHP Web Site feature, database, or Content. Antidote may also impose limits on certain features and services or restrict your access to parts or all of the Antidote Web Site without notice or liability. We reserve the right to make changes, corrections, and improvements to the Antidote Web Site, and to the products and programs described in the Site, at any time without notice.</br>
</br>
You represent, warrant and covenant that; (a) you shall not upload, post or transmit to or distribute or otherwise publish through the Antidote Web Site any materials which (i) restrict or inhibit any other user from using and enjoying the Antidote Web Site, (ii) are unlawful, threatening, abusive, libelous, defamatory, obscene, vulgar, offensive, pornographic, profane, sexually explicit or indecent, (iii) constitute or encourage conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate law, (iv) violate, plagiarize or infringe the rights of third parties including, without limitation, copyright, trademark, patent, rights of privacy or publicity or any other proprietary right, (v) contain a virus or other harmful component, (vi) contain any information, software or other material of a commercial nature, (vii) contain advertising of any kind, or (viii) constitute or contain false or misleading indications of origin or statements of fact; and (b) that you are at least eighteen (18) years old.</br>
</br>
The Antidote Web Site may contain inaccuracies or typographical errors or omissions. We regret any such errors, but will not be bound by any such errors. We do not represent or endorse the accuracy or reliability of any advice, opinion, statement, or other information displayed or distributed through the Antidote Web Site. You acknowledge that any reliance upon any such opinion, advice, statement, memorandum, or information shall be at your sole risk. We reserve the right, in our sole discretion, to correct any errors or omissions in any portion of the Antidote Web Site.</br>
</br>
The staff of Antidote.org.nz does its best to ensure that information we post to this site is both timely and accurate. But the health information changes over time and research that was accurate when posted may be superceded by more recent research. Though we may post follow-up research, and may continue to provide access to the original report, as in an archive of Healthy Foods News, for example, we don't go back and change the original report to reflect new developments. If you're looking for the most recent information on a given subject, and not the history of how the story unfolded, be sure you're not looking at an out of date report.</br>
</br>
To obtain access to certain services on our site, you may be given an opportunity to register with Antidote.org.nz. As part of any such registration process, you will select a user name and a password. You agree that the information you supply during that registration process will be accurate and complete and that you will not register under the name of, nor attempt to enter the service under the name of, another person. Antidote.org.nz reserves the right to reject or terminate any user name that, in its judgment, it deems offensive. You will be responsible for preserving the confidentiality of your password and will notify Antidote.org.nz of any known or suspected unauthorized use of your account. As part of the registration process, you agree to our Terms of Use and Privacy Policy. Please review them both carefully.</br>
</br>
By posting messages, uploading files, inputting data or engaging in any other form of communication (individually or collectively "Communications") to the Antidote Web Site, you hereby grant to Antidote and the Antidote Movement a perpetual, worldwide, irrevocable, unrestricted, non-exclusive, royalty free license to use, copy, license, sublicense, adapt, distribute, display, publicly perform, reproduce, transmit, modify, edit and otherwise exploit such Communications, in an media now known or hereafter developed. You hereby waive all rights to any claim against Antidote or the Antidote Movement for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights, and rights of attribution in connection with such Communications. You also agree to indemnify and hold Antidote and the Antidote Movement harmless against any claims or costs, including attorneys fees, arising from the use or distribution of those materials. You further grant Antidote and the Antidote Movement the right to use your name in connection with the reproduction or distribution of such material.</br>
</br>
We do not accept unsolicited materials or ideas for use or publication in Antidote's magazines, books, the Antidote Web Site, or other digital and electronic media (except in connection with forums, chat rooms, and bulletin boards on the Antidote Web Site). Antidote and the Antidote Movement shall not be responsible for the similarity of any of its content or programming in any media to materials or ideas transmitted to the Antidote Web Site.</br>
</br>
You acknowledge that transmissions to and from this Antidote Web Site are not confidential and your Communications may be read or intercepted by others. You acknowledge that by submitting Communications to Antidote, no confidential, fiduciary, contractually implied or other relationship is created between you and Antidote other than pursuant to this Agreement.</br>
</br>
THIS AGREEMENT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF HAWAII, WITHOUT REGARD TO CONFLICTS OF LAWS PROVISIONS. SOLE AND EXCLUSIVE JURISDICTION FOR ANY ACTION OR PROCEEDING ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL BE AN APPROPRIATE STATE OR FEDERAL COURT LOCATED IN THE STATE OF HAWAII.</br>
</br>
Although we make Antidote.org.nz freely accessible, we don't intend to give up our rights, or anyone else's rights, to the materials appearing on the service. The materials available through Antidote.org.nz are the property of the Antidote Movement. or its licensors, and are protected by copyright, trademark and other intellectual property laws. You are free to display and print for your personal, non-commercial use information you receive through Antidote.org.nz. But you may not otherwise reproduce any of the materials without the prior written consent of the owner. You may not distribute copies of materials found on Antidote.org.nz in any form (including by e-mail or other electronic means), without prior written permission from the owner. Of course, you're free to encourage others to access the information themselves on Antidote.org.nz and to tell them how to find it. Requests for permission to reproduce or distribute materials found on Antidote.org.nz should be sent to Daniel Suter. who developed the website for the Antidote Movement. He can be contacted at dan@antidote.org.nz Shop 6 Carnaby lane, New Brighton, 8062, Christchurch, NZ
</br></br>
We welcome links to our service. You are free to establish a hypertext link to this site so long as the link does not state or imply any sponsorship of your site by Antidote.org.nz.
</br></br>
No Framing. Without the prior written permission of Antidote.org.nz, you may not frame any of the content of Antidote.org.nz, or incorporate into another Web site or other service any intellectual property of Antidote.org.nz or any of their licensors. Requests for permission to frame our content may be sent to the Senior Content Producer, either by e-mail, or at the address above.
</br></br>
Trademarks. We don't want anyone to be confused as to which materials and services are provided by Antidote.org.nz and which aren't. You may not use any trademark or service mark appearing on Antidote.org.nz without the prior written consent of the owner of the mark. "Antidote.org.nz" and the Antidote.org.nz logo are trademarks of the Antidote Movement.
</br></br>
We respect the rights of all copyright holders and in this regard, Antidote has adopted and implemented a policy that provides for the termination in appropriate circumstances of subscribers and account holders who infringe the rights of copyright holders. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide Antidote's Copyright Agent the following information required by the Online Copyright Infringement Liability Limitation Act of the Digital :Millennium Copyright Act, 17 U.S.C. Section 512:
</br></br>
A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;
Identification of the copyright work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;
Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;
Information reasonably sufficient to permit us to contact the complaining party;
A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and
A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
</br></br>
For any questions or requests other than copyright issues, please contact Daniel Suter. who developed the website for the Antidote Movement. He can be contacted at dan@antidote.org.nz Shop 6 Carnaby lane, New Brighton, 8062, Christchurch, NZ
Some of the material on Antidote.org.nz is provided by the Associated Press or other news services. Associated Press text or other news services, photo, graphic, audio and/or video material shall not be published, broadcast, rewritten for broadcast or publication or redistributed directly or indirectly in any medium. Neither these AP materials nor any portion of these materials may be stored in a computer except for personal and non-commercial use. The AP and other news services will not be held liable for any delays, inaccuracies, errors or omissions in these materials or in the transmission or delivery of all or any part of these materials or for any damages arising from any of the foregoing.
</br></br>
Disclaimer Of Warranties And Liability
</br></br>
We work hard to make Antidote.org.nz an interesting, enjoyable and beneficial place, but we cannot guarantee that our users will always find everything to their liking. Please read this Disclaimer carefully before using Antidote.org.nz.
YOU AGREE THAT YOUR USE OF THIS SERVICE IS AT YOUR SOLE RISK. BECAUSE OF THE NUMBER OF POSSIBLE SOURCES OF INFORMATION PROVIDED THROUGH THE SERVICE AND THE UNIQUE NATURE OF EACH PERSON'S HEALTH NEEDS, YOU MAY EXPERIENCE OMISSIONS, INACCURACIES, OR OTHER PROBLEMS WITH THE INFORMATION AND ADVICE PROVIDED. IF YOU RELY ON THIS SERVICE OR ANY MATERIAL AVAILABLE THROUGH THIS SERVICE, YOU DO SO AT YOUR OWN RISK. YOU UNDERSTAND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR YOUR HEALTH THAT RESULTS FROM ANY MATERIAL AND/OR DATA DOWNLOADED FROM OR OTHERWISE PROVIDED THROUGH Antidote.org.nz.
</br></br>
THE CONTENTS OF THE Antidote.org.nz, SUCH AS TEXT, GRAPHICS, IMAGES, RECIPE RECOMMENDATIONS, AND OTHER MATERIALS ARE FOR INFORMATIONAL PURPOSES ONLY. THE CONTENT IS NOT INTENDED TO BE A SUBSTITUTE FOR PROFESSIONAL HEALTHCARE ADVICE, DIAGNOSIS, OR TREATMENT. ALWAYS SEEK THE ADVICE OF A PHYSICIAN OR OTHER QUALIFIED HEALTH PROVIDER FOR ANY HEALTH PROBLEM OR MEDICAL CONDITION. NEVER DISREGARD PROFESSIONAL HEALTHCARE ADVICE OR DELAY SEEKING HELP BECAUSE OF SOMETHING YOU HAVE READ ON THIS SITE.
</br></br>
THIS SERVICE IS PROVIDED TO YOU *AS IS,* *WITH ALL FAULTS,* AND *AS AVAILABLE.* Antidote.org.nz AND the Antidote Movement, THEIR AFFILIATES, AGENTS AND LICENSORS, CANNOT AND DO NOT WARRANT THE ACCURACY, COMPLETENESS, CURRENTNESS, NONINFRINGEMENT, OR APPROPRIATENESS FOR A PARTICULAR PURPOSE OF THE INFORMATION AVAILABLE THROUGH THE SERVICE. NOR DO THEY GUARANTEE THAT THE SERVICE WILL BE ERROR-FREE, OR CONTINUOUSLY AVAILABLE, OR THAT THE SERVICE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
</br></br>
UNDER NO CIRCUMSTANCES SHALL Antidote.org.nz OR the Antidote Movement, THEIR AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DAMAGES ARISING OUT OF USE OF Antidote.org.nz, INCLUDING, WITHOUT LIMITATION, LIABILITY FOR CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, OR SIMILAR DAMAGES, EVEN IF WE ARE ADVISED BEFOREHAND OF THE POSSIBILITY OF SUCH DAMAGES. (BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN CATEGORIES OF DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, THE LIABILITY OF Antidote.org.nz, AND the Antidote Movement, THEIR AFFILIATES, AGENTS AND LICENSORS IS LIMITED TO THE FULLEST EXTENT PERMITTED BY SUCH STATE LAW.) YOU AGREE THAT THE LIABILITY OF Antidote.org.nz AND the Antidote Movement, THEIR AFFILIATES, AGENTS AND LICENSORS, IF ANY, ARISING OUT OF ANY KIND OF LEGAL CLAIM IN ANY WAY CONNECTED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO THE SERVICE FOR THE USE OF THE SERVICE.
</br></br>
These Terms and Conditions of Use, together with the Privacy Policy and Policy for Chat Rooms and Forums, constitute the entire agreement between Antidote, the Antidote Movement, and you with respect to your use of the Antidote Web Site. Any cause of action you may have with respect to your use of the Antidote Web Site must be commenced within one (1) year after the claim or cause of action arises. If for any reason a court of competent jurisdiction finds any provision of the Agreement, or portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to effect the intent of the Agreement and the remainder of this Agreement shall continue in full force and effect. Antidote and the Antidote Movement disclaim any and all responsibility for content contained in any third party materials provided through links from the Antidote Internet site.
</br></br>
<!--#include virtual="/footer.asp" -->